### ISSUE TITLE
Build error when upgrading to v2.30.2

### ISSUE THREAD

**Issue by bjorndm** [ClickHouse/clickhouse-go#1504]
## Observed

1. I upgraded to v2.30.2
2. go build  <my binary>
3. I get a build error in this library

## Expected behaviour

Backwards compatibility should not have been broken. My project should still compile.

## Code example

Not relevant since it the build error is not in my own code.

## Error log

```log
github.com/ClickHouse/clickhouse-go/v2
../../../go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.2/conn.go:98:26: not enough arguments in call to compress.NewWriter
	have ()
	want ("github.com/ClickHouse/ch-go/compress".Level, "github.com/ClickHouse/ch-go/compress".Method)
../../../go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.2/conn.go:249:67: too many arguments in call to c.compressor.Compress
	have ("github.com/ClickHouse/ch-go/compress".Method, []byte)
	want ([]byte)
../../../go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.2/conn_http.go:233:20: not enough arguments in call to compress.NewWriter
	have ()
	want ("github.com/ClickHouse/ch-go/compress".Level, "github.com/ClickHouse/ch-go/compress".Method)
../../../go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.2/conn_http.go:259:20: not enough arguments in call to compress.NewWriter
	have ()
	want ("github.com/ClickHouse/ch-go/compress".Level, "github.com/ClickHouse/ch-go/compress".Method)
../../../go/pkg/mod/github.com/!click!house/clickhouse-go/v2@v2.30.2/conn_http.go:380:72: too many arguments in call to h.blockCompressor.Compress
	have ("github.com/ClickHouse/ch-go/compress".Method, []byte)
	want ([]byte)
```

## Details

This seem to be due to a non backwards compatible change in github.com/ClickHouse/ch-go v0.65.1 . If I downgrade to github.com/ClickHouse/ch-go v0.64.1 it compiles again.

### Environment
* [x] `clickhouse-go` version: v2.30.2
* [ x Interface: `database/sql` compatible driver
* [ ] Go version: go version go1.23.4 darwin/amd64
* [ ] Operating system: MacOS
* [ ] ClickHouse version: v2
* [ ] Is it a ClickHouse Cloud? no
* [ ] ClickHouse Server non-default settings, if any: none
* [ ] `CREATE TABLE` statements for tables involved: none
* [ ] Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary: none

**Comment by SpencerTorres** [comment]
Apologies for the trouble, I'll add a note to that release. That version should have been limited with the breaking change

**Comment by bjorndm** [comment]
Thanks for adding a note , but I think the go.mod file for that release is also incorrect. With a correctly pinned go.mod file this problem would not have occurred.

**Comment by bjorndm** [comment]
Ah, I saw you made a new release. I upgraded to v2.32.2 and because this uses the correct version of ch-go in the go.mod file, it compiles now. Thanks for the quick fix!
